entry:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\EntryRestController'
  name_prefix:  api_

search:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\SearchRestController'
  name_prefix:  api_

tag:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\TagRestController'
  name_prefix:  api_

tagging_rule:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\TaggingRuleRestController'
  name_prefix:  api_

annotation:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\AnnotationRestController'
  name_prefix:  api_

misc:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\WallabagRestController'
  name_prefix:  api_

user:
  type: rest
  resource: 'Wallabag\ApiBundle\Controller\UserRestController'
  name_prefix:  api_

config:
    type: rest
    resource: 'Wallabag\ApiBundle\Controller\ConfigRestController'
    name_prefix:  api_
